name: 'gha-private-auth'
description: 'A GitHub action to generate a token for use with other private repositories, such as private submodules'
author: 'aro5000'
branding:
  icon: 'lock'
  color: 'gray-dark'
inputs:
  pem:
    description: 'The PEM file from your GitHub app'
    default: ''
    required: true

  appId:
    description: 'The app ID of your GitHub app'
    default: ''
    required: true

  installId:
    description: 'The installation ID of your GitHub app'
    default: ''
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/aro5000/gha-private-auth@sha256:45d597a6affe3a351b728d4b8ef70a379d7976eaa8b924778a9933208c0e3b73'
  args:
    - ${{ inputs.pem }}
    - ${{ inputs.appId }}
    - ${{ inputs.installId }}