name: 'gha-private-auth'
description: 'A GitHub action to generate a token for use with other private repositories, such as private submodules'
author: 'aro5000'
branding:
  icon: 'lock'
  color: 'gray-dark'
inputs:
  pem:
    description: 'The PEM file from your GitHub app'
    default: ''
    required: true

  appId:
    description: 'The app ID of your GitHub app'
    default: ''
    required: true

  installId:
    description: 'The installation ID of your GitHub app'
    default: ''
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/aro5000/gha-private-auth@sha256:341d6e7ca956bc9e67c24c137b4eaed71b1929414caa271c03d2f54f313346c4'
  args:
    - ${{ inputs.pem }}
    - ${{ inputs.appId }}
    - ${{ inputs.installId }}